export enum IconName {
  LOGO = 'logo',
  BRAND_NAME = 'brand-name',
  WALLET_CONNECT = 'wallet-connect',
  HAMBURGER = 'hamburger',
  CASH = 'cash',
  MIXING_BOWL = 'mixing-bowl',
  USERS = 'users',
  HELP_CIRCLE = 'help-circle',
  TERMINAL = 'terminal',
  GITHUB = 'github',
  CHEVRON_DOWN = 'chevron-down',
  AVATAR = 'avatar',
  COPY = 'copy',
  FLASH_OFF = 'flash-off',
  WALLET_BIG = 'wallet-big',
  ADD_BIG = 'add-big',
  ARBITRUM_LOGO = 'arbitrum-logo',
  ETHEREUM_LOGO = 'ethereum-logo',
  POLYGON_LOGO = 'polygon-logo',
  DEFAULT_CHAIN_LOGO = 'default-chain-logo',
  EXCLAMATION_MARK = 'exclamation-mark',
}
